Update Test-Entrega.yml

diff --git a/.github/workflows/Test-Entrega.yml b/.github/workflows/Test-Entrega.yml
--- a/.github/workflows/Test-Entrega.yml
+++ b/.github/workflows/Test-Entrega.yml
@@ -13,12 +13,13 @@ jobs:
           # ls -1 lista todos los archivos
           # | grep -vE '\.(pdf|pdsprj)$' filtra y muestra los que no tienen las extensiones correctas
           # && significa que si el comando anterior encuentra una coincidencia, ejecuta lo que sigue
-          ls -1 | grep -vE '\.(pdf|pdsprj)$' && (echo "ERROR: ESE TIPO DE ARCHIVO NO HAY QUE SUBIR" && exit 1)
+          ls -1 | grep -vE '\.(pdf|pdsprj|txt|png|jpg|jpeg)$' && (echo "ERROR: ESE TIPO DE ARCHIVO NO HAY QUE SUBIR" && exit 1)
 
       - name: Creo variables por cada tipo de archivo a subir y la cantidad de archivos a subir
         run: |
           echo "ArchivoPDF=1" >> $GITHUB_ENV
           echo "ArchivoPdsprj=1" >> $GITHUB_ENV
+          echo "ArchivoTxt=1" >> $GITHUB_ENV
 
       - name: Verifica si se sube 1 archivo PDF
         run: |
@@ -37,3 +38,12 @@ jobs:
       - name: Verificar tu nombre en los archivos PROTEUS
         run: |
           ls -1 *.pdsprj | grep ${{ github.actor }} || (echo "ERROR: UN ARCHIVO PDSPRJ NO TIENE TU NOMBRE" && exit 1)
+
+      - name: Verifica si se sube 1 archivo Txt
+        run: |
+          test $(ls -1 *.txt | wc -l) -eq ${{ env.ArchivoTxt }} || (echo "ERROR: NUMERO DE ARCHIVOS .txt SUBIDOS INCORRECTO" && exit 1)
+          # -eq ${{ env.ArchivoTxt }} ahora usa la variable de entorno
+
+      - name: Verificar tu nombre en los archivos Txt
+        run: |
+          ls -1 *.txt | grep ${{ github.actor }} || (echo "ERROR: UN ARCHIVO TXT NO TIENE TU NOMBRE" && exit 1)
